apiVersion: apps/v1
kind: Deployment
metadata:
  name: railswelcomepage
  labels:
    app: rails
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: railspagecontainer
        image: bhuvanprasad/rails-default-page:latest
        ports:
        - containerPort: 3000
