apiVersion: apps/v1
kind: Deployment
metadata:
  name: railswelcomepage
  labels:
    app: rails
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: railspagecontainer
        image: 088578890509.dkr.ecr.ap-south-1.amazonaws.com/railsapp:v1
        ports:
        - containerPort: 3000
