apiVersion: apps/v1
kind: Deployment
metadata:
  name: railswelcomepage
  labels:
    app: rails
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: railspagecontainer
        image: bhuvanprasad/rails-default-page:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: railswelcomepageservice
spec:
  selector:
    app: rails
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
